XenCert/StorageHandler.py

Signed-off-by: Siddharth Vinothkumar siddharth.vinothkumar@citrix.com

CA-144196: Remove strict check while exposing LUNs per HostID.

---

src/XenCert/StorageHandlerUtil.py

CA-281950: Failed to create VDI if SR free space is too low

---

src/XenCert/StorageHandler.py

- Vendor verified below the solution, see CRD-1568 to get details
- Also tested in house with job 2152378 passed

CP-28433: nfs.soft_mount parameter timeout should not be 0

---

src/XenCert/XenCert

Signed-off-by: Xihuan Yang <xihuan.yang@citrix.com>

CP-27704:Remove the redundancy in result log print code

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py
src/XenCert/XenCertCommon.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic

2187297 for NFSv4
2187298 for NFS
2187299 for HBA
2187300 waiting hosts to run
Signed-off-by: Yuan Ren <yuan.ren@citrix.com>

CA-267058: hidden password for iscsi and cifs.

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py
src/XenCert/XenCertCommon.py

Will need to be manually re-based against Mark's changes but thought it was worth starting the review now.

Lvmfcoe support

---

src/XenCert/XenCert

CA-293888: Fix issue when execute XenCert -h

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py
src/XenCert/XenCert
src/XenCert/XenCertCommon.py
src/XenCert/XenCertLog.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic
src/XenCert/blockunblockpaths

Move some common functions to an individual module to avoid different modules trying importing each other.
Job id 
HBA 2247286
iSCSI 2247413
NFS 2247414
NFSv4 2247415
Signed-off-by: Yuan Ren <yuan.ren@citrix.com>

CA-293886: eliminate circular imports.

---

src/XenCert/StorageHandler.py

As titled.
Passed job id: 2273363
Signed-off-by: Yuan Ren <yuan.ren@citrix.com>

CA-293886: Remove the limitation that total time of disk IO test.

---

src/XenCert/StorageHandler.py

CA-304436: disk estimate test on only specified LUNs

---

src/XenCert/XenCert
src/XenCert/XenCertCommon.py

CA-304436: Renew XenCert version

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py

Based on Sonarqube report, there are some lines code never being used. 
This commit is to remove these code.

Remove code which will never be used

---

.travis.yml
src/XenCert/StorageHandler.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic
src/XenCert/blockunblockiscsipaths
src/XenCert/blockunblockpaths
tests/pylintrc

CA-329871: Remove usage of xslib.py of sm

---

src/XenCert/StorageHandlerUtil.py

CA-294634: Fix issue of finding multipath config

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py

CA-166738: Fix iSCSI exceptional issue of target without IP

---

src/XenCert/StorageHandler.py

CA-166738: Fix log description

---

src/XenCert/StorageHandler.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic
src/XenCert/blockunblockpaths

CP-32847: Support manually block/unblock path

---

src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py
src/XenCert/XenCert
src/XenCert/XenCertCommon.py
src/XenCert/XenCertLog.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic
src/XenCert/blockunblockiscsipaths
src/XenCert/blockunblockpaths

Fix sonarqube bugs  and some code smells.
XenRT test : 2934764,2934765,2934766,2934767
commit update xenrt test id : 2937422, 2937424, 2937425, 2937426
update test； 2938311,2938312,2938313,2938314

CP-33845: XenCert: fix SonarScan issue

---

src/XenCert/StorageHandlerUtil.py
src/XenCert/blockunblockiscsipaths

Found these while fixing the iSCSI multipath tests.
There is a product bug to resolve as well but these make the test suite report better results and log what it's doing.

Fix multipath

---

.travis.yml
src/XenCert/StorageHandler.py
src/XenCert/StorageHandlerUtil.py
src/XenCert/XenCert
src/XenCert/XenCertLog.py
src/XenCert/blockunblockhbapaths-brocade
src/XenCert/blockunblockhbapaths-cisco
src/XenCert/blockunblockhbapaths-qlogic
src/XenCert/blockunblockiscsipaths
src/XenCert/blockunblockpaths
src/XenCert/sm/iscsilib.py
src/XenCert/sm/lock.py
src/XenCert/sm/lvutil.py
src/XenCert/sm/metadata.py
src/XenCert/sm/mpath_cli.py
src/XenCert/sm/mpath_dmp.py
src/XenCert/sm/nfs.py
src/XenCert/sm/scsiutil.py
src/XenCert/sm/srmetadata.py
src/XenCert/sm/util.py
src/XenCert/sm/vhdutil.py
src/XenCert/sm/xs_errors.py

Update XenCert code to Python3 and move Storage dependencies to XenCert repo

CP-41104:Update XenCert code to Python3

---

src/XenCert/StorageHandler.py
src/XenCert/blockunblockpaths

1. convert the bytes into a string type
2. handle the comparison between instances of 'str' and 'int'
3715196 passed

CA-375791: Fix python3 str/bytes bug for HBA

---

src/XenCert/XenCert
src/XenCert/blockunblockiscsipaths
src/XenCert/blockunblockpaths
src/diskdatatest/atomicio.c

All test passed: 3762332 to 3762335

CA-376042: Replace tab by space chars

---

src/XenCert/StorageHandlerUtil.py

Add value 'utf-8' to encode based on Mark's comments

CA-375536 SMB test failed on rt-next with python3
